/**
 * Skill keyword catalogues used both by the parser (to bucket skills) and by
 * the room generator (to decide which themed zones light up).
 *
 * NOTE: We always match in lowercase; keep entries lower-cased.
 */

export const SKILL_KEYWORDS = {
  languages: [
    "javascript",
    "typescript",
    "python",
    "java",
    "c++",
    "c#",
    "c",
    "go",
    "golang",
    "rust",
    "ruby",
    "php",
    "kotlin",
    "swift",
    "scala",
    "r",
    "dart",
    "perl",
    "matlab",
    "bash",
    "shell",
    "sql",
  ],
  frontend: [
    "react",
    "next.js",
    "nextjs",
    "next",
    "vue",
    "nuxt",
    "angular",
    "svelte",
    "html",
    "css",
    "sass",
    "scss",
    "tailwind",
    "tailwindcss",
    "bootstrap",
    "chakra",
    "mui",
    "material-ui",
    "redux",
    "zustand",
    "framer-motion",
    "three.js",
    "threejs",
    "webgl",
    "figma",
    "ux",
    "ui",
    "ui/ux",
  ],
  backend: [
    "node.js",
    "nodejs",
    "node",
    "express",
    "nestjs",
    "fastapi",
    "django",
    "flask",
    "spring",
    "spring boot",
    "rails",
    "laravel",
    "graphql",
    "rest",
    "rest api",
    "grpc",
    "microservices",
    "ktor",
    "go fiber",
    "gin",
    ".net",
    "asp.net",
  ],
  aiMl: [
    "ai",
    "ml",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "sklearn",
    "keras",
    "nlp",
    "llm",
    "langchain",
    "huggingface",
    "transformers",
    "computer vision",
    "opencv",
    "neural network",
    "openai",
    "rag",
    "fine-tuning",
    "yolov",
    "yolo",
  ],
  databases: [
    "postgresql",
    "postgres",
    "mysql",
    "mongodb",
    "mongo",
    "redis",
    "sqlite",
    "firebase",
    "firestore",
    "supabase",
    "prisma",
    "dynamodb",
    "elasticsearch",
    "neo4j",
    "cassandra",
    "snowflake",
    "bigquery",
  ],
  devops: [
    "docker",
    "kubernetes",
    "k8s",
    "ci/cd",
    "github actions",
    "jenkins",
    "gitlab ci",
    "circleci",
    "terraform",
    "ansible",
    "linux",
    "nginx",
    "helm",
    "argocd",
  ],
  cloud: [
    "aws",
    "amazon web services",
    "ec2",
    "s3",
    "lambda",
    "cloudfront",
    "azure",
    "gcp",
    "google cloud",
    "vercel",
    "netlify",
    "heroku",
    "digitalocean",
    "cloudflare",
    "render",
  ],
  cybersecurity: [
    "cybersecurity",
    "security",
    "owasp",
    "penetration testing",
    "pentest",
    "vulnerability",
    "ethical hacking",
    "burp suite",
    "metasploit",
    "wireshark",
    "encryption",
    "cryptography",
    "malware",
    "threat",
    "siem",
    "soc",
    "ids",
    "ips",
  ],
  mobile: [
    "react native",
    "flutter",
    "android",
    "ios",
    "kotlin",
    "swift",
    "swiftui",
    "jetpack compose",
    "expo",
    "xamarin",
    "ionic",
    "mobile app",
  ],
  dataScience: [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "plotly",
    "tableau",
    "power bi",
    "powerbi",
    "data analysis",
    "data analytics",
    "data visualization",
    "etl",
    "spark",
    "apache spark",
    "hadoop",
    "kafka",
    "airflow",
    "dbt",
  ],
  tools: [
    "git",
    "github",
    "gitlab",
    "jira",
    "confluence",
    "vscode",
    "vim",
    "postman",
    "insomnia",
    "swagger",
    "notion",
    "slack",
    "trello",
    "figma",
    "photoshop",
  ],
} as const;

export type SkillCategory = keyof typeof SKILL_KEYWORDS;

export const SECTION_HEADINGS: Record<string, string[]> = {
  experience: [
    "experience",
    "work experience",
    "professional experience",
    "employment",
    "internship",
    "internships",
  ],
  education: ["education", "academics", "academic background", "qualifications"],
  projects: ["projects", "personal projects", "academic projects", "selected projects"],
  skills: ["skills", "technical skills", "core skills", "technologies", "tech stack"],
  achievements: [
    "achievements",
    "awards",
    "honors",
    "honours",
    "accomplishments",
  ],
  certifications: ["certifications", "certificates", "courses"],
  publications: ["publications", "papers", "research"],
  summary: ["summary", "profile", "about", "objective"],
};
